apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookstack
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/bookstack/hosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: bookstack
      namespace: bookstack
  # Remove dependency for now since the MariaDB is already running
  # dependsOn:
  #   - name: mariadb
