apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mariadb-app
  namespace: flux-system
spec:
  interval: 5m
  path: ./k8s/apps/mariadb/hosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 10m
