apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  chart:
    spec:
      version: 20.5.7
  values:
    auth:
      username: maria_user
