apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mariadb
  namespace: database
spec:
  chart:
    spec:
      chart: mariadb
      version: 20.5.7
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: database
