apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: mariadb
  namespace: flux-system
spec:
  interval: 5m
  url: oci://registry-1.docker.io/bitnamicharts/mariadb
  ref:
    semver: "*"
