apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - config.yaml

# Optional: Add any lab-specific patches here
# patchesStrategicMerge:
#   - patches/lab-specific-patch.yaml
