apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      version: '0.14.9'
  values:
    controller:
      image:
        tag: v0.14.9
    speaker:
      image:
        tag: v0.14.9
