apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
spec:
  template:
    spec:
      containers:
      - name: bookstack
        image: lscr.io/linuxserver/bookstack:version-v25.05
