apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstack
  namespace: bookstack
  labels:
    app: bookstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bookstack
  template:
    metadata:
      labels:
        app: bookstack
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: bookstack
        image: lscr.io/linuxserver/bookstack:latest
        ports:
        - containerPort: 80
          name: http
        env:
        # User and Group IDs
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Asia/Kuwait"
        
        # Application Configuration
        - name: APP_URL
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: app-url
        - name: APP_KEY
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: app-key
        
        # Database Configuration (correct variable names)
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: db-port
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: db-username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: db-password
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: bookstack-config
              key: db-database
        
        # Optional: Queue configuration for async tasks
        - name: QUEUE_CONNECTION
          value: "database"
        
        volumeMounts:
        - name: bookstack-data
          mountPath: /config
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
      
      volumes:
      - name: bookstack-data
        persistentVolumeClaim:
          claimName: bookstack-data
      
      # Ensure BookStack starts after MariaDB is ready
      initContainers:
      - name: wait-for-mariadb
        image: busybox:1.35
        command:
        - sh
        - -c
        - |
          echo "Waiting for MariaDB to be ready..."
          until nc -z mariadb.database.svc.cluster.local 3306; do
            echo "MariaDB not ready, waiting 5 seconds..."
            sleep 5
          done
          echo "MariaDB is ready!"
