apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: bookstack
  app.kubernetes.io/instance: bookstack
  app.kubernetes.io/component: wiki

# Add namespace to all resources
namespace: bookstack
