apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bookstack-data
  namespace: bookstack
  labels:
    app: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
