apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-idreaminyaml-com
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: ezarnosky@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging-idreaminyaml-com
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-idreaminyaml-com
            key: api-token
      selector:
        dnsZones:
        - "idreaminyaml.com"
