apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - clusterissuer-prod.yaml
  - clusterissuer-staging.yaml
  - sealed-secret.yaml

patchesStrategicMerge:
  - version-patch.yaml
