apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  # Domain-specific resources for idreaminyaml.com
  - clusterissuer-prod-idreaminyaml-com.yaml
  - clusterissuer-staging-idreaminyaml-com.yaml
  - sealed-secret-idreaminyaml-com.yaml
  # Domain-specific resources for technodumpster.com
  - clusterissuer-prod-technodumpster-com.yaml
  - clusterissuer-staging-technodumpster-com.yaml
  - sealed-secret-technodumpster-com.yaml
  # Domain-specific resources for zarnosky.online
  - clusterissuer-prod-zarnosky-online.yaml
  - clusterissuer-staging-zarnosky-online.yaml
  - sealed-secret-zarnosky-online.yaml
  # Domain-specific resources for mydevopsguys.com
  - clusterissuer-prod-mydevopsguys-com.yaml
  - clusterissuer-staging-mydevopsguys-com.yaml
  - sealed-secret-mydevopsguys-com.yaml

patchesStrategicMerge:
  - version-patch.yaml
