---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token-Zarnosky-online
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBkg+E72DQ5pl7c3KNuzkD2zp+FROinvBQCWKBy2X+HBjokrKgufjF6i7ngHP3visAu7K/FFBMkZIaOdMjiu7N1MlYLrOki4cecnPE+wak7nPR5cS1+nqAzYfikcSgBOVYy4pqg3tMjPIiwODDwNK/IMUocsGKdekXi6iaSFWvkm4Qw+p39TW2y5ySaLZfTswblA4pbPkxc3VXi9/aCYKhWW2mJMe6GayJsr8RfoC/MFXn90WIUTigp705+kRtNjKCIxVqZ5sO4lTZ8fRLSPIwnuojncSGoQDE6GwmcOGvYm3mIiJq60FtdcNUIdp0qupUnaz5mujftLqHI159mC5ifxsU7DEULcF1j6KjqJmQNTwRhTip2zud6LqqqqGNnqnFQ1zrlAmUFJ2oNkrIIJsvIUUvoKxtqTM85m/1YkCITlDRkaIyWCONS+Poox7c+Jl7Usi3Kvwj0y7pKA0or0fNcOzv1S2jeLTkllGXsVR/qwMmE4cwYvBbNJ/+7SWi95EmnUO3QoWrFA95xPDPGq+zIy7h2i2d/wYSdU1WrcQKNDbZnsYUbANQ953+rsqTDkICiZ4tcr2spXdo3L5O2PVrOLXmJS5QMAlFk/2xbLfGPqMqDKZAT6p+Af0gAI3LSlK3YL2/fjDRS++cWvkBhpYdSQh4b4cVrW3HHcV/GNIfGgRkSb0hOmR1kXhjj8TfphBQ8ibm6sbJF8TKDlZD6ZnDGTdajKl7n54Kjv4ImdTMUsw8KQucGjWvD
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token-Zarnosky-online
      namespace: cert-manager
