apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - namespace.yaml
  - shared-config-namespace.yaml
  - clusterissuer-staging.yaml
  # Uncomment after testing with staging
  # - clusterissuer-prod.yaml

patchesStrategicMerge:
  - version-patch.yaml

replacements:
- source:
    kind: Secret
    name: cloudflare-secrets
    namespace: shared-config
    fieldPath: data.acme-email
  targets:
  - select:
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.email
- source:
    kind: Secret
    name: cloudflare-secrets
    namespace: shared-config
    fieldPath: data.cloudflare-zone
  targets:
  - select:
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.solvers.[dns01.cloudflare].selector.dnsZones.0
