apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - clusterissuer-staging.yaml
  # Uncomment after testing with staging
  # - clusterissuer-prod.yaml

patchesStrategicMerge:
  - version-patch.yaml

# Remove replacements - they don't work reliably with cross-namespace secrets
# We'll use a different approach
