apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

replacements:
- source:
    kind: ConfigMap
    name: cert-manager-config
    fieldPath: data.acme-email
  targets:
  - select:
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.email
- source:
    kind: ConfigMap
    name: cert-manager-config
    fieldPath: data.cloudflare-zone
  targets:
  - select:
      kind: ClusterIssuer
    fieldPaths:
    - spec.acme.solvers.[dns01.cloudflare].selector.dnsZones.0
