apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  chart:
    spec:
      version: '1.14.4'
  values:
    image:
      tag: "v1.14.4"
    webhook:
      image:
        tag: "v1.14.4"
    cainjector:
      image:
        tag: "v1.14.4"
